apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  namespace: aula
  labels:
    run: busypod
  name: busypod
spec:
  containers:
  - args:
    - sleep
    - 1d
    image: busybox
    name: busypod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
