apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: aula
  name: simulador-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: standart

