apiVersion: v1
kind: Service
metadata:
  name: apache-svc
  namespace: aula
spec:
  type: NodePort
  selector:
    camada: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008
