apiVersion: v1
kind: Service
metadata:
  name: banco-svc
  namespace: aula
spec:
  type: NodePort
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007

