apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox-pod
  name: busybox-pod
spec:
  containers:
  - args:
    - sleep
    - 1d
    image: busybox
    name: busybox-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
